### ISSUE TITLE
Form 2: Suspected ADR Reporting Form

### ISSUE THREAD

**Issue by canaryGrapher** [canaryGrapher/ADR-portal#7]

**Comment by canaryGrapher** [comment]
The page files for each form for the ADR Reporting section are in the `./app/routes/medical-device-reporting` directory. Create a new file for the screen accordingly. These are the pages that need to be completed for the first form:
- [x] Page 1
- [x] Page 2
- [x] Page 3
    - [x] Page 3-i
    - [x] Page 3-ii
    - [x] Page 3-iii
    - [x] Page 3-iv
    - [x] Page 3-v
- [x] Page 4

**Comment by canaryGrapher** [comment]
Assignments:
@mihirpenugonda : Page 1 & 2
@Parthiv-M : Page 3-i and 3-ii
@sxkshi : Page 3-iii and 3-iv
@canaryGrapher : Page 3-v and 4

**Comment by mihirpenugonda** [comment]
@mihirpenugonda : Creation of the following component

![image](https://user-images.githubusercontent.com/7721970/157306540-53681599-9c9e-4cb1-bba5-2152cab3fcfd.png)

@Parthiv-M @sxkshi @canaryGrapher use the component created in form2-mihir in your forms

**Comment by mihirpenugonda** [comment]
Update: 
1) Component for input Radio Button has been created find it under the Components -> Forms folder
2) Creation of Layout File for Suspected ADR Reporting under Layouts folder

**Comment by canaryGrapher** [comment]
All changes made and merged with `main`
